# Generated by Django 3.0.3 on 2020-02-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
