# Generated by Django 3.0.3 on 2020-02-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_delete_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
